### ISSUE TITLE
Bad sorting

### ISSUE THREAD

**Issue by Vasago** [Shadez/wowarmory#18]
There are problems with sorting - there should be always according to biggest values not less and after you click on next page - the sorting you have set - is gone again - so you sort by the highest rank - click on next page - sorting is reseted ...

**Comment by Vasago** [comment]
Sorting is still bad - Now after [230] when you click again on sorting (wins, rating, rank) it doesnt work - once it should sort "DESC" click again it should sort "ASC" but it does not work now.

Arena teams should be Sorted according to rating not ranks.

**Comment by Shadez** [comment]
Should be fixed in <a href="http://github.com/Shadez/wowarmory/commit/f886f0a2251baba66b519b300cad71a14a7af59c">238 rev.</a>

**Comment by Vasago** [comment]
Still not fully fixed - now sorting according to best rating - ok BUT 

Still when you click on rating again it should sort to DEST click again and sort ASC again in all lines like wins, loses, rank or rating but this is not working ... Thx
