### ISSUE TITLE
Revision 394 problems on TC

### ISSUE THREAD

**Issue by Vasago** [Shadez/wowarmory#71]
Here are several issues now with 394 on trinity:
1) there are wrong values of personal rating in arena stats instead of 2000 there is 400 etc, sometimes even members in team are not shown correctly

2) When i am trying to access guild tab on character there is error:
<b>Warning</b>:  Missing argument 1 for Characters::Characters(), called in /var/www/armory/includes/classes/class.guilds.php on line 209 and defined in <b>/var/www/armory/includes/classes/class.characters.php</b> on line <b>244</b><br />

3) New talents are broken - you can see only primary tab talents when you click on secondary it will not show anything - also it is not showing where you have talents spend - just 0-0 but in fron page of character you have shown like 3/17/51 but when you want to see them exactly nothing is shown

4) Some errors now:
ArmoryDatabaseHandler::_query : unable to execute SQL query (SELECT `gmlevel` FROM `account` WHERE `id`=65458 LIMIT 1). MySQL error: none
ArmoryDatabaseHandler::_query : unable to execute SQL query (SELECT `name`, `Quality`, `ItemLevel`, `displayid`, `SellPrice`, `BuyPrice`, `Flags2`, `RequiredDisenchantSkill` FROM `item_template` WHERE `entry`=4026 LIMIT 1). MySQL error: Unknown column 'Flags2' in 'field list'<br />
Items::GetRandomPropertiesData : unable to get rand_data FROM `ARMORYDBPREFIX_randomproperties` for id -40
Arenateams::GetTeamList : unable to get player list for arena team 881 (Gentleman)

**Comment by Vasago** [comment]
2) Is fixed in 397 
Other are still present including 1) and 4) number 3) is present only in firefox opera shows correctly the talents ...

**Comment by Shadez** [comment]
1) I need characters databaseв dump with characters/arena teams (because I haven't public server all tests ) to try to fix this. If you can share with me, please do it.
3) Can't reproduce this bug on Mozilla Firefox 3.6.9. Try to remove browser cache.
4) These errors are not so bad, you can just ignore it

**Comment by Vasago** [comment]
http://filebeam.com/586ced6147f564c9fe6a4884c67a1f86 here is dump from 4 characters from two teams hope it helps character DB is big so only extracted 4 of them hope it helps also for this problem with achievements: http://github.com/Shadez/wowarmory/issues/closed#issue/22

**Comment by Vasago** [comment]
Here is part two http://filebeam.com/2b816152ada2c9b852345ad97bdb18e5 for armory data for these characters ... Hope it is complete now...

**Comment by Vasago** [comment]
Any news about this?

**Comment by Vasago** [comment]
All fixed now thank you - please dont forget for this bug visible on first look - thank you http://github.com/Shadez/wowarmory/issues/closed#issue/22

**Comment by Shadez** [comment]
If I'm understood right, core rewrites some achievements/criterias after player log in world. Have no idea why and still unable to find the reason of this issue. May be I should add check for achievements which are already exists in `character_achievement` table but I'm afraid that server will create too much queries to DB...

**Comment by Vasago** [comment]
I dont think it is problem when you take it as select from character database ...
